# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5782c2af4e05248d32f61391b42e829768ab3782740f59ede6db9a928eb1861659f23ff90ac0127514192edb83f5a8623ba0289dd5c39cb13d9288e57147f019

test:
  secret_key_base: fc05f318f612bb831ba6ddcb8719d989b411577b992633e5a2846e7ca3f89e8d0ad18ba20a689d3214850ed66485e85051f2093713b6d0d8ab878099732224e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
